#!/usr/bin/env bash
# Collect normalised static-check output into $1.
#
# Runs once on the head tree and once on the base tree, always from that tree's
# own root. Output is one sorted line per issue, so the diff engine can treat
# the two runs as comparable sets.
#
# NOTE: this script ends by restoring the tree with `git checkout -- .`. That is
# correct in CI, where the checkout is clean. Running it against a working tree
# with uncommitted edits will discard them.

# Deliberately no `-e`: every check here exits non-zero when it finds issues,
# which is the normal case, not a script failure.
set -uo pipefail

OUT="${1:?usage: collect-static.sh <output-dir>}"
mkdir -p "$OUT"

# Byte-order sorting, so the two trees produce comparable lists even if the head
# and base runners ever differ in locale. `sort` under a UTF-8 locale ignores
# leading punctuation, which would order `.oxfmtrc.json` after `AGENTS.md`.
export LC_ALL=C

# Paths kept out of the lint and formatter deltas. `.agents/` holds vendored
# skill docs that came with the EmDash template, `.github/ci/` holds these
# scripts, and the two .d.ts files are regenerated by `astro check` on every
# run — nobody reviewing a PR can act on drift in any of them.
EXCLUDE='^(\.agents/|\.github/ci/|dist/|emdash-env\.d\.ts$|worker-configuration\.d\.ts$)'

# Read-only checks run concurrently. `astro check` is the long pole at ~15s and
# oxlint finishes underneath it in well under a second, so this is close to free.
(
	# `astro check` prints ANSI colour and its own format — not tsc's:
	#   src/utils/dates.ts:21:2 - error ts(2322): Type 'string' is not ...
	# Strip the colour, keep only diagnostic lines (dropping the code frames and
	# the "Result (30 files)" summary, which changes with the count and would
	# diff as a permanent phantom issue), then rewrite " - " into ": " so each
	# line reads as plain unix format and parsers.unix can read it.
	pnpm typecheck 2>&1 |
		sed -r 's/\x1b\[[0-9;]*m//g' |
		grep -E '^[^[:space:]]+:[0-9]+:[0-9]+ - (error|warning) ' |
		sed -E 's/^([^:]+):([0-9]+):([0-9]+) - (.*)$/\1:\2:\3: \4/' |
		grep -Ev "$EXCLUDE" |
		sort >"$OUT/typecheck.txt"
) &
(
	# oxlint already emits unix format and repo-root-relative paths, which is
	# the same shape `git diff --name-only` gives — the formatter gate depends
	# on those two matching.
	pnpm exec oxlint -f unix . 2>&1 |
		grep -E '^[^:[:space:]][^:]*:[0-9]+:[0-9]+:' |
		grep -Ev "$EXCLUDE" |
		sort -u >"$OUT/lint.txt"
) &
wait

# The formatters REWRITE files, so they run after the read-only checks. The set
# of files they modified is exactly the formatting debt — no separate --check
# pass needed, and it yields paths rather than a count.
#
# Two formatters because oxfmt cannot parse .astro (oxc-project/oxc#19715).
# Each reads its own ignore file -- .oxfmtignore and .prettierignore -- so the
# two never rewrite the same file. Passing --ignore-path is what stops oxfmt
# reading .prettierignore, which would exclude everything but .astro and leave
# it formatting nothing.
pnpm exec oxfmt --ignore-path .oxfmtignore . >/dev/null 2>&1
pnpm exec prettier --write "**/*.astro" >/dev/null 2>&1
git diff --name-only | grep -Ev "$EXCLUDE" | sort >"$OUT/format.txt"
git checkout -- .

# Never let a missing file break the render step.
#
# `touched.txt` is deliberately NOT in this list. The workflow writes it into
# the same directory on the head tree only, and the formatter gate reads its
# ABSENCE as "the step that lists this PR's files did not run" — an empty file
# here would turn that failure into a silent pass.
for f in typecheck lint format; do
	[ -f "$OUT/$f.txt" ] || : >"$OUT/$f.txt"
done

wc -l "$OUT"/*.txt
